- name: Configure Docker YUM repository
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable
    baseurl: "{{ docker_yum_repo_url }}"
    gpgkey: "{{ docker_yum_repo_gpg }}"
    gpgcheck: yes
- name: Ensure docker is installed and up to date
  package:
    name: docker-ce-{{ docker_version }}
    state: installed
- name: Ensure docker configuration directory exists
  file:
    path: /etc/docker
    state: directory
- name: Create docker daemon.json
  copy:
    dest: /etc/docker/daemon.json
    content: "{{ docker_daemon_json_data | to_nice_json }}\n"
- name: Create sysconfig file
  template:
    src: sysconfig-docker.j2
    dest: /etc/sysconfig/docker
    force: no
- name: Create service override directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
- name: Create service override file
  copy:
    src: service-override.conf
    dest: /etc/systemd/system/docker.service.d/override.conf
    force: no
  register: docker_service_override_result
- name: Execute daemon reload
  systemd:
    daemon_reload: yes
  when: docker_service_override_result.changed
- name: Ensure docker started
  service:
    name: docker
    state: started
- name: Ensure docker service is enabled
  service:
    name: docker
    enabled: yes
