- name: Configure Docker YUM repository
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable
    baseurl: "{{ docker_yum_repo_url }}"
    gpgkey: "{{ docker_yum_repo_gpg }}"
    gpgcheck: yes
- name: Ensure docker is installed and up to date
  package: name=docker-ce-{{ docker_version }} state=latest
- name: Ensure docker configuration directory exists
  file: path=/etc/docker state=directory
- name: Create docker daemon.json
  copy: dest=/etc/docker/daemon.json content={{ docker_daemon_json_data }}
- name: Ensure docker started
  service: name=docker state=started
- name: Ensure docker service is enabled
  service: name=docker enabled=yes
